services:
  cycbox-cli:
    image: ghcr.io/cycbox/cycbox:latest
    # Access serial devices on the host
    privileged: true
    volumes:
      - /dev:/dev
      - ./config.lua:/config/config.lua:ro
    command:
      - "--config"
      - "/config/config.lua"
    restart: unless-stopped
